import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
u,s,vt=np.linalg.svd(a)
print("Left Singular Matrix:")
print(u)
print("Singular matrix:")
print(s)
print("Right Singular Matrix:")
print(vt)
sigma=np.zeros((a.shape[0],a.shape[1]))
np.fill_diagonal(sigma,s)
b=u.dot(sigma.dot(vt))
print("Reconstructed Matrix:\n",b)
